// Factorio Auto Splitter -- generated by autosplitter/factorio
// Build:           Steam Space Age (build dfdf4a..)
// Module SHA256:   dfdf4a206141fa4af8ad48f46c87b865c4b681d6bc420e0ca6f5f1c0812873bb
// Generated at:    2026-04-27T19:10:24Z
// Generator:       v0.0.0-20260427160335-e4f07bf9be1d+dirty
// Milestones:      32 (31 research, 1 event)
//
// Pointer chain (verified runtime, see Factoio_memory.md):
//   factorio.exe + 0x2847368                                  -> GlobalContext*
//   GlobalContext + 0x68                                            -> Game*  (NULL when no game loaded)
//   Game          + 0x188                                            -> Map*
//   Map           + 0x198                                            -> uint64 tick (60/s, 0 before save loaded)
//   Map           + 0x3E8                                            -> forces.begin (vector<Force*>)
//   forces[forceID=1]                                                       -> Force*  (player)
//   Force         + 0x50                                             -> TechnologyMap*
//   TechnologyMap + 0x8                                              -> entries.begin (TechnologyEntry[40])
//   entries[techID]+ 0x24                                            -> uint32 current_level (>= 1 means researched)

state("factorio") {
    // Static base address of the GlobalContext pointer (in factorio.exe .data).
    // Reading this pointer-path returns Game* via GlobalContext+0x68.
    ulong gamePointer : 0x2847368, 0x68;
}

startup {
    settings.Add("research", true, "Research milestones");
    settings.SetToolTip("research", "Splits triggered when a research is completed.");

    settings.Add("trig_steam_power", true, "Steam Power", "research");
    settings.Add("trig_electronics", true, "Electronics", "research");
    settings.Add("trig_auto_science", true, "Automation Science Pack", "research");
    settings.Add("trig_steel_axe", true, "Steel Axe", "research");
    settings.Add("trig_oil_processing", true, "Oil Processing", "research");
    settings.Add("trig_uranium_processing", true, "Uranium Processing", "research");
    settings.Add("trig_space_platform", true, "Space Platform", "research");
    settings.Add("trig_space_science", true, "Space Science Pack", "research");
    settings.Add("trig_recycling", true, "Recycling", "research");
    settings.Add("trig_holmium_processing", true, "Holmium Processing", "research");
    settings.Add("trig_electromagnetic_plant", true, "Electromagnetic Plant", "research");
    settings.Add("trig_electromagnetic_science", true, "Electromagnetic Science Pack", "research");
    settings.Add("trig_jellynut", true, "Jellynut", "research");
    settings.Add("trig_yumako", true, "Yumako", "research");
    settings.Add("trig_heating_tower", true, "Heating Tower", "research");
    settings.Add("trig_agriculture", true, "Agriculture", "research");
    settings.Add("trig_biochamber", true, "Biochamber", "research");
    settings.Add("trig_artificial_soil", true, "Artificial Soil", "research");
    settings.Add("trig_bioflux", true, "Bioflux", "research");
    settings.Add("trig_bacteria_cultivation", true, "Bacteria Cultivation", "research");
    settings.Add("trig_bioflux_processing", true, "Bioflux Processing", "research");
    settings.Add("trig_agricultural_science", true, "Agricultural Science Pack", "research");
    settings.Add("trig_tungsten_carbide", true, "Tungsten Carbide", "research");
    settings.Add("trig_calcite_processing", true, "Calcite Processing", "research");
    settings.Add("trig_foundry", true, "Foundry", "research");
    settings.Add("trig_big_mining_drill", true, "Big Mining Drill", "research");
    settings.Add("trig_tungsten_steel", true, "Tungsten Steel", "research");
    settings.Add("trig_metallurgic_science", true, "Metallurgic Science Pack", "research");
    settings.Add("trig_lithium_processing", true, "Lithium Processing", "research");
    settings.Add("trig_cryogenic_plant", true, "Cryogenic Plant", "research");
    settings.Add("trig_cryogenic_science", true, "Cryogenic Science Pack", "research");

    settings.Add("events", true, "Event milestones");
    settings.SetToolTip("events", "Splits triggered by game events (run end, etc).");
    settings.Add("space_age_clear", true, "Solar System Edge", "events");

    refreshRate = 30;

    // Track Game Time using Factorio's internal tick counter (60 ticks/s).
    // The user can still toggle to Real Time via LiveSplit Compare menu.
    timer.CurrentTimingMethod = TimingMethod.GameTime;

    // Segment-aware lookup: a single segment in the .lss may be addressed
    // by either its display name ("Steam Power") or its internal trigger ID
    // ("trig_steam_power"). Both keys map to the same tech prototype name.
    vars.SegmentToTech = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);
    vars.SegmentToTech["Steam Power"] = "steam-power";
    vars.SegmentToTech["trig_steam_power"] = "steam-power";
    vars.SegmentToTech["Electronics"] = "electronics";
    vars.SegmentToTech["trig_electronics"] = "electronics";
    vars.SegmentToTech["Automation Science Pack"] = "automation-science-pack";
    vars.SegmentToTech["trig_auto_science"] = "automation-science-pack";
    vars.SegmentToTech["Steel Axe"] = "steel-axe";
    vars.SegmentToTech["trig_steel_axe"] = "steel-axe";
    vars.SegmentToTech["Oil Processing"] = "oil-processing";
    vars.SegmentToTech["trig_oil_processing"] = "oil-processing";
    vars.SegmentToTech["Uranium Processing"] = "uranium-processing";
    vars.SegmentToTech["trig_uranium_processing"] = "uranium-processing";
    vars.SegmentToTech["Space Platform"] = "space-platform";
    vars.SegmentToTech["trig_space_platform"] = "space-platform";
    vars.SegmentToTech["Space Science Pack"] = "space-science-pack";
    vars.SegmentToTech["trig_space_science"] = "space-science-pack";
    vars.SegmentToTech["Recycling"] = "recycling";
    vars.SegmentToTech["trig_recycling"] = "recycling";
    vars.SegmentToTech["Holmium Processing"] = "holmium-processing";
    vars.SegmentToTech["trig_holmium_processing"] = "holmium-processing";
    vars.SegmentToTech["Electromagnetic Plant"] = "electromagnetic-plant";
    vars.SegmentToTech["trig_electromagnetic_plant"] = "electromagnetic-plant";
    vars.SegmentToTech["Electromagnetic Science Pack"] = "electromagnetic-science-pack";
    vars.SegmentToTech["trig_electromagnetic_science"] = "electromagnetic-science-pack";
    vars.SegmentToTech["Jellynut"] = "jellynut";
    vars.SegmentToTech["trig_jellynut"] = "jellynut";
    vars.SegmentToTech["Yumako"] = "yumako";
    vars.SegmentToTech["trig_yumako"] = "yumako";
    vars.SegmentToTech["Heating Tower"] = "heating-tower";
    vars.SegmentToTech["trig_heating_tower"] = "heating-tower";
    vars.SegmentToTech["Agriculture"] = "agriculture";
    vars.SegmentToTech["trig_agriculture"] = "agriculture";
    vars.SegmentToTech["Biochamber"] = "biochamber";
    vars.SegmentToTech["trig_biochamber"] = "biochamber";
    vars.SegmentToTech["Artificial Soil"] = "artificial-soil";
    vars.SegmentToTech["trig_artificial_soil"] = "artificial-soil";
    vars.SegmentToTech["Bioflux"] = "bioflux";
    vars.SegmentToTech["trig_bioflux"] = "bioflux";
    vars.SegmentToTech["Bacteria Cultivation"] = "bacteria-cultivation";
    vars.SegmentToTech["trig_bacteria_cultivation"] = "bacteria-cultivation";
    vars.SegmentToTech["Bioflux Processing"] = "bioflux-processing";
    vars.SegmentToTech["trig_bioflux_processing"] = "bioflux-processing";
    vars.SegmentToTech["Agricultural Science Pack"] = "agricultural-science-pack";
    vars.SegmentToTech["trig_agricultural_science"] = "agricultural-science-pack";
    vars.SegmentToTech["Tungsten Carbide"] = "tungsten-carbide";
    vars.SegmentToTech["trig_tungsten_carbide"] = "tungsten-carbide";
    vars.SegmentToTech["Calcite Processing"] = "calcite-processing";
    vars.SegmentToTech["trig_calcite_processing"] = "calcite-processing";
    vars.SegmentToTech["Foundry"] = "foundry";
    vars.SegmentToTech["trig_foundry"] = "foundry";
    vars.SegmentToTech["Big Mining Drill"] = "big-mining-drill";
    vars.SegmentToTech["trig_big_mining_drill"] = "big-mining-drill";
    vars.SegmentToTech["Tungsten Steel"] = "tungsten-steel";
    vars.SegmentToTech["trig_tungsten_steel"] = "tungsten-steel";
    vars.SegmentToTech["Metallurgic Science Pack"] = "metallurgic-science-pack";
    vars.SegmentToTech["trig_metallurgic_science"] = "metallurgic-science-pack";
    vars.SegmentToTech["Lithium Processing"] = "lithium-processing";
    vars.SegmentToTech["trig_lithium_processing"] = "lithium-processing";
    vars.SegmentToTech["Cryogenic Plant"] = "cryogenic-plant";
    vars.SegmentToTech["trig_cryogenic_plant"] = "cryogenic-plant";
    vars.SegmentToTech["Cryogenic Science Pack"] = "cryogenic-science-pack";
    vars.SegmentToTech["trig_cryogenic_science"] = "cryogenic-science-pack";

    // TechIDs is built at runtime by walking TechnologyMap.entries -- the
    // index of each prototype in the array depends on mod/DLC load order
    // and changes per save, so a baked-in cache would be brittle.
    vars.TechIDs = new Dictionary<string, ushort>();

    // Setting ID lookup so we can still honour the on/off checkboxes per milestone.
    vars.TechToSetting = new Dictionary<string, string>();
    vars.TechToSetting["steam-power"] = "trig_steam_power";
    vars.TechToSetting["electronics"] = "trig_electronics";
    vars.TechToSetting["automation-science-pack"] = "trig_auto_science";
    vars.TechToSetting["steel-axe"] = "trig_steel_axe";
    vars.TechToSetting["oil-processing"] = "trig_oil_processing";
    vars.TechToSetting["uranium-processing"] = "trig_uranium_processing";
    vars.TechToSetting["space-platform"] = "trig_space_platform";
    vars.TechToSetting["space-science-pack"] = "trig_space_science";
    vars.TechToSetting["recycling"] = "trig_recycling";
    vars.TechToSetting["holmium-processing"] = "trig_holmium_processing";
    vars.TechToSetting["electromagnetic-plant"] = "trig_electromagnetic_plant";
    vars.TechToSetting["electromagnetic-science-pack"] = "trig_electromagnetic_science";
    vars.TechToSetting["jellynut"] = "trig_jellynut";
    vars.TechToSetting["yumako"] = "trig_yumako";
    vars.TechToSetting["heating-tower"] = "trig_heating_tower";
    vars.TechToSetting["agriculture"] = "trig_agriculture";
    vars.TechToSetting["biochamber"] = "trig_biochamber";
    vars.TechToSetting["artificial-soil"] = "trig_artificial_soil";
    vars.TechToSetting["bioflux"] = "trig_bioflux";
    vars.TechToSetting["bacteria-cultivation"] = "trig_bacteria_cultivation";
    vars.TechToSetting["bioflux-processing"] = "trig_bioflux_processing";
    vars.TechToSetting["agricultural-science-pack"] = "trig_agricultural_science";
    vars.TechToSetting["tungsten-carbide"] = "trig_tungsten_carbide";
    vars.TechToSetting["calcite-processing"] = "trig_calcite_processing";
    vars.TechToSetting["foundry"] = "trig_foundry";
    vars.TechToSetting["big-mining-drill"] = "trig_big_mining_drill";
    vars.TechToSetting["tungsten-steel"] = "trig_tungsten_steel";
    vars.TechToSetting["metallurgic-science-pack"] = "trig_metallurgic_science";
    vars.TechToSetting["lithium-processing"] = "trig_lithium_processing";
    vars.TechToSetting["cryogenic-plant"] = "trig_cryogenic_plant";
    vars.TechToSetting["cryogenic-science-pack"] = "trig_cryogenic_science";
}

init {
    var moduleBase = modules.First().BaseAddress;
    vars.GlobalContextStaticPtr = (System.IntPtr)((long)moduleBase + 0x2847368L);
    vars.ForceID = (byte)1;
    vars.EntriesBegin = (long)0;
    vars.LastResolvedEntries = (long)0;
    vars.TechMapPtr = (long)0;
    vars.MapPtr = (long)0;
    vars.TickValue = (long)0;
    vars.LastTick = (long)0;
    vars.GameLoaded = false;
    vars.JustLoaded = false;

    // Runtime resolver for MSVC std::basic_string<char>. Returns null on any
    // failure (NULL pointers, implausible size/capacity, unreadable memory)
    // so the caller can skip silently rather than crashing on bad slots.
    vars.ReadStdString = (Func<long, string>)((long stringAddr) => {
        if (stringAddr == 0) return null;
        long size = memory.ReadValue<long>((IntPtr)(stringAddr + 16L));
        long cap = memory.ReadValue<long>((IntPtr)(stringAddr + 24L));
        if (size <= 0L || size > 256L) return null;
        if (cap < 0L || cap > (1L << 30)) return null;
        long dataAddr = (cap <= 15L)
            ? stringAddr
            : memory.ReadValue<long>((IntPtr)stringAddr);
        if (dataAddr == 0L) return null;
        byte[] bytes = memory.ReadBytes((IntPtr)dataAddr, (int)size);
        if (bytes == null || bytes.Length == 0) return null;
        return System.Text.Encoding.UTF8.GetString(bytes);
    });

    // TimerModel wraps the LiveSplitState and exposes Split/SkipSplit/UndoSplit
    // -- we need it from split{} to mark intermediate segments as "skipped"
    // (no time recorded) when the player researches techs out of segment order.
    vars.TimerModel = new LiveSplit.Model.TimerModel { CurrentState = timer };

    // Per-segment de-duplication of split-rejection diagnostics so we don't
    // flood the LiveSplit log with one line per refresh tick.
    vars.LoggedSplitReasons = new Dictionary<int, string>();

    print("[autosplitter/factorio] init: module=0x" + moduleBase.ToInt64().ToString("X"));
}

update {
    // Note: avoid identifiers `game`, `memory`, `modules`, `timer`, `current`, `old`, `vars`,
    // `settings`, `version`, `refreshRate` -- they are reserved by the ASL runtime.
    long gcPtr = memory.ReadValue<long>((System.IntPtr)vars.GlobalContextStaticPtr);
    long gamePtr = (gcPtr != 0) ? memory.ReadValue<long>((System.IntPtr)(gcPtr + 0x68L)) : 0;
    long mapPtr = (gamePtr != 0) ? memory.ReadValue<long>((System.IntPtr)(gamePtr + 0x188L)) : 0;
    long forcesBegin = (mapPtr != 0) ? memory.ReadValue<long>((System.IntPtr)(mapPtr + 0x3E8L)) : 0;
    long forcePtr = (forcesBegin != 0) ? memory.ReadValue<long>((System.IntPtr)(forcesBegin + 8L * (long)vars.ForceID)) : 0;
    long techMapPtr = (forcePtr != 0) ? memory.ReadValue<long>((System.IntPtr)(forcePtr + 0x50L)) : 0;
    long entriesBegin = (techMapPtr != 0) ? memory.ReadValue<long>((System.IntPtr)(techMapPtr + 0x8L)) : 0;
    long tick = (mapPtr != 0) ? memory.ReadValue<long>((System.IntPtr)(mapPtr + 0x198L)) : 0;

    bool nowLoaded = (entriesBegin != 0);
    bool wasLoaded = (bool)vars.GameLoaded;
    vars.JustLoaded = (nowLoaded && !wasLoaded);
    vars.GameLoaded = nowLoaded;
    vars.EntriesBegin = entriesBegin;
    vars.TechMapPtr = techMapPtr;
    vars.MapPtr = mapPtr;
    vars.LastTick = (long)vars.TickValue;
    vars.TickValue = tick;

    // Build TechIDs map dynamically the first time we see this entries.begin.
    // Entries are reallocated when the player loads a different save (different
    // mod loadout = different prototype count and load order), so we re-scan
    // whenever entries.begin moves. Also retry if the previous build produced
    // an empty dictionary -- otherwise a transient memory read failure during
    // the scan could leave us with no tech mappings until the save is reloaded.
    var prevTechIDs = (Dictionary<string, ushort>)vars.TechIDs;
    bool needsResolve = entriesBegin != 0L &&
        (entriesBegin != (long)vars.LastResolvedEntries || prevTechIDs.Count == 0);
    if (needsResolve) {
        long entriesEnd = memory.ReadValue<long>((IntPtr)(techMapPtr + 0x10L));
        long count = (entriesEnd - entriesBegin) / 40L;
        if (count > 0L && count < 8192L) {
            var techIDs = new Dictionary<string, ushort>();
            var readString = (Func<long, string>)vars.ReadStdString;
            for (int i = 0; i < (int)count; i++) {
                long entryAddr = entriesBegin + 40L * i;
                long protoPtr = memory.ReadValue<long>((IntPtr)entryAddr);
                if (protoPtr == 0L) continue;
                // std::string `name` lives at TechnologyPrototype + 0x8 (right after vtable).
                string name = readString(protoPtr + 0x8L);
                if (string.IsNullOrEmpty(name)) continue;
                if (!techIDs.ContainsKey(name)) techIDs[name] = (ushort)i;
            }
            // Only commit LastResolvedEntries on a successful (non-empty) build,
            // so an all-null scan retries on the next frame instead of locking
            // in a permanently empty TechIDs until save reload.
            if (techIDs.Count > 0) {
                vars.TechIDs = techIDs;
                vars.LastResolvedEntries = entriesBegin;
                print("[autosplitter/factorio] resolved " + techIDs.Count
                    + " tech IDs from " + count + " entries (entries.begin=0x"
                    + entriesBegin.ToString("X") + ")");
            }
        }
    }
}

start {
    // Auto-start when the in-game tick crosses from 0 to >0 -- happens on
    // a fresh save start. For loaded saves (tick already > 0), fall back to
    // the GameLoaded transition so the timer also starts when attaching mid-run.
    long tick = (long)vars.TickValue;
    long last = (long)vars.LastTick;
    bool freshStart = (last == 0L && tick > 0L);
    bool loadedMidRun = (bool)vars.JustLoaded && tick > 0L;
    return (freshStart || loadedMidRun);
}

gameTime {
    // Sync LiveSplit Game Time with Factorio's internal tick counter.
    // 60 ticks per second is the engine constant; pause/menu freezes ticks
    // automatically so we do not need an isLoading block.
    if (!(bool)vars.GameLoaded) return null;
    long tick = (long)vars.TickValue;
    if (tick <= 0L) return TimeSpan.Zero;
    return TimeSpan.FromSeconds((double)tick / 60.0);
}

isLoading {
    // Tick freezes during loads/pause -- gameTime{} naturally stops, so we
    // explicitly say "not loading" to keep Real Time running uninterrupted.
    return false;
}

split {
    // Segment-aware with out-of-order tolerance:
    //   1. Identify the next milestone segment whose tech is researched (start
    //      from the currently active segment, walk forward).
    //   2. If nothing ahead is researched -- return false.
    //   3. If the matching segment IS the current one -- normal split.
    //   4. If the match is later -- SkipSplit() the in-between segments so
    //      they get a dash (no time) instead of a fast-fired fake split, then
    //      return true to fire the actual split on the matching segment.
    //
    // An unknown segment in the gap (one not registered in SegmentToTech)
    // aborts the lookahead -- we never auto-skip a segment we don't recognise
    // because the user might be using it for a manual checkpoint.
    if (!(bool)vars.GameLoaded) return false;
    long entriesBegin = (long)vars.EntriesBegin;
    if (entriesBegin == 0L) return false;

    var run = timer.Run;
    int idx = timer.CurrentSplitIndex;
    if (idx < 0 || idx >= run.Count) return false;

    var segMap     = (Dictionary<string, string>)vars.SegmentToTech;
    var settingMap = (Dictionary<string, string>)vars.TechToSetting;
    var techIDs    = (Dictionary<string, ushort>)vars.TechIDs;
    if (techIDs.Count == 0) return false;  // resolver not run yet

    // Diagnostics: log the reason we don't fire on the *current* segment so the
    // user can correlate "I researched X but split didn't fire" with what the
    // script actually saw. Logged at most once per (idx, reason) combination
    // to avoid spamming the LiveSplit log every refresh tick.
    var loggedReasons = (Dictionary<int, string>)vars.LoggedSplitReasons;
    var logSplitReason = (Action<int, string>)((int slot, string reason) => {
        string prev;
        if (!loggedReasons.TryGetValue(slot, out prev) || prev != reason) {
            loggedReasons[slot] = reason;
            print("[autosplitter/factorio] split idx=" + slot + " " + reason);
        }
    });

    int target = -1;
    for (int i = idx; i < run.Count; i++) {
        var seg = run[i];
        string segName = (seg != null) ? seg.Name : null;
        if (string.IsNullOrEmpty(segName) || !segMap.ContainsKey(segName)) {
            if (i == idx) {
                logSplitReason(i, "seg=" + (segName ?? "<null>") + " not in SegmentToTech -- bail");
                return false;
            }
            break;                        // unknown ahead -- never auto-skip past
        }
        string techName = segMap[segName];
        if (settingMap.ContainsKey(techName) && !settings[settingMap[techName]]) {
            if (i == idx) logSplitReason(i, "tech=" + techName + " disabled in settings");
            continue;
        }
        if (!techIDs.ContainsKey(techName)) {
            if (i == idx) logSplitReason(i, "tech=" + techName + " missing from runtime TechIDs (count=" + techIDs.Count + ")");
            continue;
        }
        ushort techID = techIDs[techName];
        long entryAddr = entriesBegin + 40L * (long)techID;
        uint level = memory.ReadValue<uint>((System.IntPtr)(entryAddr + 0x24L));
        if (level >= 1) { target = i; break; }
        if (i == idx) logSplitReason(i, "tech=" + techName + " id=" + techID + " level=" + level + " (waiting)");
    }
    if (target < 0) return false;

    if (target > idx) {
        var model = (LiveSplit.Model.TimerModel)vars.TimerModel;
        // Skip every segment between the current index and the matching one;
        // each SkipSplit advances CurrentSplitIndex by one and marks the
        // skipped segment with no split time. Safety counter prevents an
        // infinite loop if LiveSplit refuses to advance (e.g. on the final
        // segment); we never need more than run.Count steps anyway.
        int safety = 0;
        while (timer.CurrentSplitIndex < target && safety < run.Count) {
            model.SkipSplit();
            safety++;
        }
        if (timer.CurrentSplitIndex != target) return false;  // skip stalled
    }
    return true;
}

reset {
    return false;
}

exit {
}

shutdown {
}
